In [1]:
import autorootcwd


In [2]:
from src.data import heart_disease, titanic, artificial
from src.irls import IRLS
from sklearn.model_selection import train_test_split

X_heart, y_heart = heart_disease.prepare_data()

# split the data into train and test sets
X_train_heart, X_test_heart, y_train_heart, y_test_heart = train_test_split(
    X_heart,
    y_heart,
    test_size=0.2,
    random_state=42,
)


Dropped colinear columns: ['sex_1.0', 'cp_4.0', 'fbs_1.0', 'restecg_2.0', 'exang_1.0', 'slope_1.0', 'slope_2.0']


In [3]:
irls_custom = IRLS(interaction_pairs=None, max_iter=1000, tol=1e-6)


In [4]:
irls_custom.fit(X_train_heart, y_train_heart)


array([[-4.28083419],
       [ 0.01235451],
       [ 0.01812425],
       [ 0.00895681],
       [-0.01491515],
       [ 0.63473263],
       [ 1.19060765],
       [ 0.26816191],
       [-1.55484484],
       [-1.8133621 ],
       [-0.83920047],
       [-1.44064618],
       [ 0.43419487],
       [-0.3420269 ],
       [ 0.37199293],
       [-0.74751876],
       [-1.02215801]])

In [5]:
irls_custom.predict(X_test_heart)

array([[0.63211589],
       [0.73953082],
       [0.81991708],
       [0.62084716],
       [0.62137992],
       [0.77563011],
       [0.97979585],
       [0.99518935],
       [0.37466399],
       [0.53209538],
       [0.10551064],
       [0.01782063],
       [0.72418407],
       [0.98581774],
       [0.99839348],
       [0.05546814],
       [0.0321386 ],
       [0.6599076 ],
       [0.99811542],
       [0.08148165],
       [0.70688738],
       [0.03481233],
       [0.99510022],
       [0.02379876],
       [0.99588537],
       [0.03905814],
       [0.32295678],
       [0.91969968],
       [0.9551589 ],
       [0.54897616],
       [0.17842706],
       [0.72799281],
       [0.03676694],
       [0.54366742],
       [0.39861758],
       [0.72023225],
       [0.98541365],
       [0.47684083],
       [0.9926727 ],
       [0.26253284],
       [0.96188132],
       [0.30275015],
       [0.92015837],
       [0.04826085],
       [0.28099576],
       [0.95891726],
       [0.04568296],
       [0.114

In [6]:
X_train_heart

array([[ 29., 130., 204., ...,   0.,   1.,   0.],
       [ 57., 150., 126., ...,   0.,   1.,   0.],
       [ 69., 160., 234., ...,   0.,   1.,   0.],
       ...,
       [ 59., 140., 177., ...,   0.,   0.,   0.],
       [ 61., 140., 207., ...,   0.,   0.,   0.],
       [ 57., 128., 303., ...,   0.,   1.,   0.]], dtype=float32)

In [7]:
# print full X_train_heart np array
import numpy as np

np.set_printoptions(threshold=np.inf)
# X_train_heart

# print var and std of each col of np arr
for i in range(0, X_train_heart.shape[1]):
    print(np.var(X_train_heart[:, i]), np.std(X_train_heart[:, i]))


82.65236 9.091334
330.19733 18.171333
2319.6902 48.163162
502.85794 22.424494
1.4051834 1.1854043
0.8005089 0.8947116
3.7074816 1.9254822
0.2253432 0.47470328
0.08264463 0.2874798
0.14343281 0.37872523
0.20558707 0.45341712
0.11776858 0.34317428
0.25 0.5
0.008196162 0.09053266
0.22402838 0.47331637
0.06531317 0.25556442
